[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cryptocore"
version = "0.2.0"
description = "Command line file encryption with AES-128"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pycryptodome>=3.20,<4"
]

[project.scripts]
cryptocore = "cryptocore.cli:main"

[tool.setuptools.packages.find]
where = ["src"]